ci: add more e2e tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -118,6 +118,179 @@ jobs:
           name: cartesi-binaries
           path: cartesi-*
 
+  local_e2e_test_only_l1_2_apps:
+    name: e2e tests send only L1
+    runs-on: ubuntu-latest
+    env:
+      CARTESI_FEATURE_ESPRESSO_READER_ENABLED: true
+      COMPOSE_BAKE: true
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Install Foundry
+        uses: foundry-rs/foundry-toolchain@v1
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build docker compose
+        run: |
+          docker compose build
+
+      - name: Run docker compose
+        run: |
+          docker compose up --wait
+
+      - name: Deploy Echo Dapp 01
+        env:
+          ACCOUNT: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
+          PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
+          RPC_URL: "http://localhost:8545"
+        run: |
+          docker compose exec cartesi_node_espresso cartesi-rollups-cli app deploy -n echo-dapp01 -t applications/echo-dapp/ -v -D 0x8579fd0c000000000000000000000000b6b39fb3dd926a9e3fbc7a129540eebea3016a6c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d903
+          sleep 10
+          docker compose logs --timestamps cartesi_node_espresso
+
+      - name: Deploy Echo Dapp 02
+        env:
+          ACCOUNT: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
+          PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
+          RPC_URL: "http://localhost:8545"
+        run: |
+          docker compose exec cartesi_node_espresso \
+            cartesi-rollups-cli app deploy -n echo-dapp02 \
+              -t applications/echo-dapp/ -v \
+              -D 0x8579fd0c000000000000000000000000b6b39fb3dd926a9e3fbc7a129540eebea3016a6c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d903 \
+              --salt 0000000000000000000000000000000000000000000000000000000000000001
+          sleep 10
+          docker compose logs --timestamps cartesi_node_espresso
+
+      - name: App 01 Send L1 InputBox transaction
+        env:
+          INPUT: "0xdead01beef"
+          INPUT_BOX_ADDRESS: "0xB6b39Fb3dD926A9e3FBc7A129540eEbeA3016a6c"
+          APPLICATION_ADDRESS: "0x01e800bbE852aeb27cE65604709134Ea63782c6B"
+        run: |
+          cast send \
+              --mnemonic "test test test test test test test test test test test junk" \
+              --rpc-url "http://localhost:8545" \
+              $INPUT_BOX_ADDRESS "addInput(address,bytes)(bytes32)" $APPLICATION_ADDRESS $INPUT
+
+      - name: App 02 Send L1 InputBox transaction
+        env:
+          INPUT: "0xdead02beef"
+          INPUT_BOX_ADDRESS: "0xB6b39Fb3dD926A9e3FBc7A129540eEbeA3016a6c"
+          APPLICATION_ADDRESS: "0x154E3997c4CF3Fda877a0A884A04F9eEf65B2346"
+        run: |
+          cast send \
+              --mnemonic "test test test test test test test test test test test junk" \
+              --rpc-url "http://localhost:8545" \
+              $INPUT_BOX_ADDRESS "addInput(address,bytes)(bytes32)" $APPLICATION_ADDRESS $INPUT
+
+      - name: Cartesi node Espresso logs
+        run: docker compose logs --timestamps cartesi_node_espresso
+
+      - name: Espresso dev node logs
+        run: docker compose logs --timestamps espresso-dev-node
+
+      - name: Query Database for Output
+        run: |
+          MAX_RETRIES=30
+          for i in $(seq 1 $MAX_RETRIES); do
+            RESULT=$(docker compose exec db psql -U postgres -d rollupsdb -t -c "SELECT * FROM public.output;")
+            if [[ "$RESULT" =~ dead01beef && "$RESULT" =~ dead02beef ]]; then
+              echo "Result found: $RESULT"
+              exit 0
+            fi
+            echo "Result: $RESULT"
+            echo "Waiting for result... attempt $i"
+            sleep 5
+          done
+          echo "Timeout reached: result not found"
+          docker compose logs --timestamps cartesi_node_espresso
+          exit 1
+
+  local_e2e_test_only_l2:
+    name: e2e tests (Espresso Local) send only L2
+    runs-on: ubuntu-latest
+    env:
+      CARTESI_FEATURE_ESPRESSO_READER_ENABLED: true
+      COMPOSE_BAKE: true
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Install Foundry
+        uses: foundry-rs/foundry-toolchain@v1
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build docker compose
+        run: |
+          docker compose build
+
+      - name: Run docker compose
+        run: |
+          docker compose up --wait
+
+      - name: Deploy Echo Dapp
+        env:
+          ACCOUNT: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
+          PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
+          RPC_URL: "http://localhost:8545"
+        run: |
+          docker compose exec cartesi_node_espresso cartesi-rollups-cli app deploy -n echo-dapp -t applications/echo-dapp/ -v -D 0x8579fd0c000000000000000000000000b6b39fb3dd926a9e3fbc7a129540eebea3016a6c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d903
+          sleep 10
+          docker compose logs --timestamps cartesi_node_espresso
+
+      - name: Checkout nonodo
+        uses: actions/checkout@v4
+        with:
+          repository: Calindra/nonodo
+          submodules: recursive
+          path: ./nonodo
+
+      - name: Send L2 EIP 712 transaction
+        working-directory: ./nonodo/eip712-client-js
+        env:
+          SENDER_PRIVATE_KEY: ${{ secrets.SENDER_PRIVATE_KEY }}
+          TRANSACTION_BASE_URL: http://localhost:8080
+          APP_ADDRESS: "0x01e800bbE852aeb27cE65604709134Ea63782c6B"
+          INPUT: "0xdeadbeefdeadbeef"
+        run: |
+          npm i
+          node index.js || true
+          sleep 10
+
+      - name: Cartesi node Espresso logs
+        run: docker compose logs --timestamps cartesi_node_espresso
+
+      - name: Espresso dev node logs
+        run: docker compose logs --timestamps espresso-dev-node
+
+      - name: Query Database for Output
+        run: |
+          MAX_RETRIES=30
+          for i in $(seq 1 $MAX_RETRIES); do
+            RESULT=$(docker compose exec db psql -U postgres -d rollupsdb -t -c "SELECT * FROM public.output;")
+            if [[ "$RESULT" =~ "deadbeefdeadbeef" ]]; then
+              echo "Result found: $RESULT"
+              exit 0
+            fi
+            echo "Result: $RESULT"
+            echo "Waiting for result... attempt $i"
+            sleep 5
+          done
+          echo "Timeout reached: result not found"
+          docker compose logs --timestamps cartesi_node_espresso
+          exit 1
+
   integration_test:
     name: Integration tests (Local Espresso Dev Node)
     runs-on: ubuntu-latest
